// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseApp, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SXi7j6Z5H1bGB2WQGTvrqjRdhzDjEZA',
    appId: '1:106303308002:android:f093442d29c04d434c1ebb',
    messagingSenderId: '106303308002',
    projectId: 'flutter-recipedia',
    storageBucket: 'flutter-recipedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHna3GGT_EVVv3ZzLMHa7trcyZAU_UNH0',
    appId: '1:106303308002:ios:a2980f7769437b6d4c1ebb',
    messagingSenderId: '106303308002',
    projectId: 'flutter-recipedia',
    storageBucket: 'flutter-recipedia.appspot.com',
    iosClientId:
        '106303308002-k90tob3vgvl7dvudlgdj3ghpotucenm7.apps.googleusercontent.com',
    iosBundleId: 'favteo.com.flutterRecipedia',
  );
}
